//! The `#[derive(Redact)]` implementation: a per-principal view type plus the
//! `view_for` that builds it.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{Data, DeriveInput, Field, Fields, Meta, Type};

/// How a field appears in the generated view.
enum Visibility {
    /// No attribute: the field as-is, for every viewer.
    Public,
    /// `#[hidden]`: per-viewer via `OwnerRedact` (owner full, others residue).
    HiddenOwner,
    /// `#[hidden(conceal)]`: the `Conceal` residue, for every viewer.
    HiddenConceal,
    /// `#[hidden(from = all)]`: omitted from the view entirely.
    HiddenAll,
}

pub fn derive(input: DeriveInput) -> syn::Result<TokenStream> {
    let principal = parse_principal(&input)?;

    let Data::Struct(data) = &input.data else {
        return Err(syn::Error::new_spanned(
            &input,
            "Redact can only be derived for structs.\n\
             Redaction is field-level: each field is public, hidden, or concealed.\n\
             Use a struct with named fields.",
        ));
    };
    let Fields::Named(fields) = &data.fields else {
        return Err(syn::Error::new_spanned(
            &data.fields,
            "Redact needs named fields.\n\
             Each field's visibility is declared by an attribute on the named field.\n\
             Convert the tuple/unit struct to one with named fields.",
        ));
    };

    let name = &input.ident;
    let view_name = format_ident!("{}View", name);
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    let mut view_fields = Vec::new();
    let mut view_inits = Vec::new();

    for field in &fields.named {
        let ident = field.ident.as_ref().expect("named field");
        let ty = &field.ty;
        match classify(field)? {
            Visibility::Public => {
                view_fields.push(quote!(pub #ident: #ty));
                view_inits.push(quote!(#ident: ::core::clone::Clone::clone(&self.#ident)));
            }
            Visibility::HiddenOwner => {
                view_fields.push(quote! {
                    pub #ident: <#ty as ::ironstate_aggregate::OwnerRedact<#principal>>::View
                });
                view_inits.push(quote! {
                    #ident: ::ironstate_aggregate::OwnerRedact::redact_for(&self.#ident, viewer)
                });
            }
            Visibility::HiddenConceal => {
                view_fields.push(quote! {
                    pub #ident: <#ty as ::ironstate_aggregate::Conceal>::Concealed
                });
                view_inits.push(quote! {
                    #ident: ::ironstate_aggregate::Conceal::conceal(&self.#ident)
                });
            }
            Visibility::HiddenAll => {
                // Omitted from the view: no field, no initializer.
            }
        }
    }

    Ok(quote! {
        /// A per-principal view generated by `#[derive(Redact)]`.
        #[derive(::core::clone::Clone, ::core::fmt::Debug, ::core::cmp::PartialEq)]
        pub struct #view_name {
            #(#view_fields,)*
        }

        impl #impl_generics ::ironstate_aggregate::View<#principal> for #name #ty_generics
            #where_clause
        {
            type Output = #view_name;
            fn view_for(&self, viewer: &#principal) -> #view_name {
                #view_name {
                    #(#view_inits,)*
                }
            }
        }
    })
}

fn parse_principal(input: &DeriveInput) -> syn::Result<Type> {
    let mut principal = None;
    for attr in &input.attrs {
        if !attr.path().is_ident("redact") {
            continue;
        }
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("principal") {
                principal = Some(meta.value()?.parse::<Type>()?);
                Ok(())
            } else {
                Err(meta.error("unknown `redact` option; expected `principal = SomeType`"))
            }
        })?;
    }
    principal.ok_or_else(|| {
        syn::Error::new_spanned(
            input,
            "missing principal.\n\
             Redaction needs to know who the viewers are.\n\
             Add `#[redact(principal = YourPrincipalType)]` above the struct.",
        )
    })
}

fn classify(field: &Field) -> syn::Result<Visibility> {
    let mut visibility = Visibility::Public;
    for attr in &field.attrs {
        if !attr.path().is_ident("hidden") {
            continue;
        }
        visibility = match &attr.meta {
            Meta::Path(_) => Visibility::HiddenOwner,
            Meta::List(_) => {
                let mut found = None;
                attr.parse_nested_meta(|meta| {
                    if meta.path.is_ident("conceal") {
                        found = Some(Visibility::HiddenConceal);
                        Ok(())
                    } else if meta.path.is_ident("from") {
                        let value: syn::Ident = meta.value()?.parse()?;
                        if value == "all" {
                            found = Some(Visibility::HiddenAll);
                            Ok(())
                        } else {
                            Err(meta.error("expected `from = all`"))
                        }
                    } else {
                        Err(meta.error(
                            "unknown `hidden` form; expected `#[hidden]`, \
                             `#[hidden(conceal)]`, or `#[hidden(from = all)]`",
                        ))
                    }
                })?;
                found.ok_or_else(|| {
                    syn::Error::new_spanned(
                        attr,
                        "empty `hidden(...)`; use `#[hidden]`, `#[hidden(conceal)]`, \
                         or `#[hidden(from = all)]`",
                    )
                })?
            }
            Meta::NameValue(_) => {
                return Err(syn::Error::new_spanned(
                    attr,
                    "`hidden` does not take a value; use `#[hidden]`, \
                     `#[hidden(conceal)]`, or `#[hidden(from = all)]`",
                ));
            }
        };
    }
    Ok(visibility)
}
